# Generated by Django 4.0.6 on 2022-07-26 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InTimeBio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=8, verbose_name='Country')),
                ('smoker', models.BooleanField(default=False, verbose_name='Smoker?')),
                ('hip', models.FloatField(default=100, verbose_name='Hip in cm')),
                ('waist', models.FloatField(default=110, verbose_name='Waist in cm')),
                ('wrist', models.FloatField(default=20, verbose_name='Wrist in cm')),
                ('neck', models.FloatField(default=40, verbose_name='Neck in cm')),
                ('current_heart_rate', models.FloatField(default=60, verbose_name='Current Heart Rate in bpm')),
                ('daily_activity_level', models.CharField(choices=[('low', 'L'), ('medium', 'M'), ('high', 'H')], default='medium', max_length=8, verbose_name='Daily Activity')),
                ('blood_pressure_sys', models.FloatField(default=120, verbose_name='Sys Blood Pressure in mmHg')),
                ('blood_pressure_dia', models.FloatField(default=80, verbose_name='Dia Blood Pressure in mmHg')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.person')),
            ],
        ),
        migrations.CreateModel(
            name='BloodTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urea', models.FloatField(verbose_name='Urea')),
                ('cr', models.IntegerField(verbose_name='Creatinine')),
                ('hba1c', models.FloatField(verbose_name='Hemoglobin A1C')),
                ('chol', models.FloatField(verbose_name='Cholesterol')),
                ('tg', models.FloatField(verbose_name='Triglycerides')),
                ('hdl', models.FloatField(verbose_name='High-density lipoproteins')),
                ('ldl', models.FloatField(verbose_name='Low-density lipoproteins')),
                ('vldl', models.FloatField(verbose_name='Very Low-density lipoproteins')),
                ('result', models.CharField(max_length=2, null=True, verbose_name='Blood Test Result')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.person')),
            ],
        ),
    ]
